{% set name = "reprexlite" %}
{% set version = "0.4.3" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/reprexlite-{{ version }}.tar.gz
  sha256: 7724b6ac19f356d2eb82158a9068241328577b4d61022d4f60fbbe6b6e2a2c23

build:
  number: 0
  noarch: python
  entry_points:
    - reprex=reprexlite.cli:app
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - importlib-metadata
    - libcst
    - python >=3.6
    - typer

test:
  imports:
    - reprexlite
  commands:
    - pip check
    - reprex --help
  requires:
    - pip

about:
  home: https://github.com/jayqi/reprexlite
  summary: Render reproducible examples of Python code for sharing.
  license: MIT
  license_file: LICENSE
  doc_url: https://jayqi.github.io/reprexlite/
  dev_url: https://github.com/jayqi/reprexlite

extra:
  recipe-maintainers:
    - jayqi
