{% set name = "reprexlite" %}
{% set version = "1.0.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/reprexlite-{{ version }}.tar.gz
  sha256: 13801f66f84ef41ee8cd045d55ccd0883695708f9edf6b4d300951ad6a08ec8b

build:
  number: 0
  noarch: python
  entry_points:
    - reprex=reprexlite.cli:app
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - flit-core
  run:
    - cyclopts >=3
    - libcst
    - platformdirs
    - python >={{ python_min }}
    - typing-extensions

test:
  imports:
    - reprexlite
  commands:
    - pip check
    - reprex --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/jayqi/reprexlite
  summary: Render reproducible examples of Python code for sharing.
  license: MIT
  license_file: LICENSE
  doc_url: https://jayqi.github.io/reprexlite/
  dev_url: https://github.com/jayqi/reprexlite

extra:
  recipe-maintainers:
    - jayqi
