{% set name = "reprexlite" %}
{% set version = "0.5.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/reprexlite-{{ version }}.tar.gz
  sha256: 3e8968f23619df1289c0d66bc200c0c79e577d199caf6205645cfc9dc4749de2

build:
  number: 1
  noarch: python
  entry_points:
    - reprex=reprexlite.cli:app
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - importlib-metadata
    - libcst
    - python >={{ python_min }}
    - typer

test:
  imports:
    - reprexlite
  commands:
    - pip check
    - reprex --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/jayqi/reprexlite
  summary: Render reproducible examples of Python code for sharing.
  license: MIT
  license_file: LICENSE
  doc_url: https://jayqi.github.io/reprexlite/
  dev_url: https://github.com/jayqi/reprexlite

extra:
  recipe-maintainers:
    - jayqi
